### ISSUE TITLE
Fail to create a new connection for the connection pool

### ISSUE THREAD

**Issue by Bruno-Marley** [TheOnlyArtz/Seday#2]
When I use "node main.js" the following error appears in the console:
`Creating a pool connected to localhost:28015
Server is listening on port 3000
Entering slow growth mode
Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to localhost:28015\nFull error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}","message":"Failed to connect to localhost:28015\nFull error:\n{\"code\":\"ECONNREFUSED\",\"errno\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}.","isOperational":true}`

And when I enter "http://localhost:3000/" this message appears:
`ReqlDriverError: None of the pools have an opened connection and failed to open a new one.`

**Comment by shanegarrygifford** [comment]
Make sure you have a rethinkdb running, download a rethinkdb here: https://www.rethinkdb.com/docs/install/

I'm no expert so if this doesn't help then I've no clue on how to fix the problem.

**Comment by ETLegacyy** [comment]
@BrunoMarley289 have you ran rethinkdb? Also what operating system are you using?

**Comment by Bruno-Marley** [comment]
I already solved the problem thanks, the issue can be closed.

**Comment by lingeswrn** [comment]
> I already solved the problem thanks, the issue can be closed.

I am getting the same error. can you please explain how to resolve this?

**Comment by splatboydev** [comment]
Me too

**Comment by TheOnlyArtz** [comment]
Hey! You guys probably need to create a RethinkDB database on your systems, please check out RethinkDB's website for installation instructions @splatboy20081 @lingeswrn
