### ISSUE TITLE
Redirect URL

### ISSUE THREAD

**Issue by 5h0ne** [TheOnlyArtz/Seday#3]
I've tried everything I could think of to fix this but I'm having no luck.

{"redirect_uri": ["Not a well formed URL."]}

**Comment by TheOnlyArtz** [comment]
> I've tried everything I could think of to fix this but I'm having no luck.
> 
> {"redirect_uri": ["Not a well formed URL."]}

Hey, I'm really sorry for the late reply, but can you please provide more information regarding the issue?

**Comment by ETLegacyy** [comment]
@TheOnlyArtz when i was playing with it, it done the same thing. It happens when you click Login through Discord. The url has an undefined as well `https://discordapp.com/api/oauth2/authorize?client_id=363888422714212352&scope=identify%20guilds&permissions=0&redirect_uri=undefined&response_type=code`.

**Comment by ETLegacyy** [comment]
https://github.com/TheOnlyArtz/Seday/blob/master/src/Website/views/Login.ejs#L22

**Comment by Bruno-Marley** [comment]
It's because you're missing the redirect_uri in `config.json`.
I'm having the same problem, but I do not know which redirect_uri to put.

https://github.com/TheOnlyArtz/Seday/blob/master/src/Website/config.json.example

**Comment by TheOnlyArtz** [comment]
The redirect_uri should be: `http://localhost:3000/oauth/redirect`
I think. I will check tomorrow and get back to you with a concrete answer.

**Comment by TheOnlyArtz** [comment]
@BrunoMarley289 So it's the day after, the redirect_uri is indeed `https://localhost:3000/oauth/redirect`
Note that you need to set it on the bot's OAUTH page in Discord's dashboard too!

**Comment by TheOnlyArtz** [comment]
So, I've patched many of Sedays issues today! I'm looking forward to keep maintaining it, I've fixed some issues like incorrect sending of payloads and bot's attempts to reconnect to the websocket

**Comment by Bruno-Marley** [comment]
For me, `https://localhost:3000/oauth/redirect` was not working, so I put `http://localhost:3000/oauth/redirect` and it worked.

**Comment by Bruno-Marley** [comment]
@TheOnlyArtz It is missing to declare the constant "token_type", I declared in line 93 and I think it is working but the file is wrong.
https://github.com/TheOnlyArtz/Seday/blob/master/src/Website/routes/get.js

**Comment by TheOnlyArtz** [comment]
Correct, fixing it right now, what do you mean by `the file is wrong` ?

**Comment by Bruno-Marley** [comment]
I fixed it in my code but in the repo file, it was wrong, but now that you've corrected it, it's all right.
