### ISSUE TITLE
I am getting a driver error

### ISSUE THREAD

**Issue by Veucci** [TheOnlyArtz/Seday#8]
```
Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to localhost:28015\nFull error:\n{\"errno\":-4078,\"code\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}","message":"Failed to connect to localhost:28015\nFull error:\n{\"errno\":-4078,\"code\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}.","isOperational":true}
ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
```
Can you help me please?

**Comment by TheOnlyArtz** [comment]
> ```
> Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to localhost:28015\nFull error:\n{\"errno\":-4078,\"code\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}","message":"Failed to connect to localhost:28015\nFull error:\n{\"errno\":-4078,\"code\":\"ECONNREFUSED\",\"syscall\":\"connect\",\"address\":\"127.0.0.1\",\"port\":28015}.","isOperational":true}
> ReqlDriverError: None of the pools have an opened connection and failed to open a new one.
> ```
> Can you help me please?

Hey there it seems like you don't have a RethinkDB instance running on your machine.

**Comment by Veucci** [comment]
thanks, it worked.
